version: "3.8"
services:
    nextjs:
        ports:
            - 3000:3000
        expose:
            - "3000"
        build:
            context: client/.
            dockerfile: Dockerfile
        container_name: nextjs
        restart: unless-stopped
        volumes:
            - ./client:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        depends_on:
            - django
        command: npm run start
        environment:
            VIRTUAL_HOST: juicify.app
            LETSENCRYPT_HOST: juicify.app
            LETSENCRYPT_EMAIL: kamilow97@gmail.com

    django:
        build:
            context: server/.
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: django
        ports:
            - 8000:8000
        expose:
            - "8000"
        volumes:
            - ./server:/django
        depends_on:
            - postgres
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        environment:
            VIRTUAL_HOST: server.juicify.app
            LETSENCRYPT_HOST: server.juicify.app
            LETSENCRYPT_EMAIL: kamilow97@gmail.com

    postgres:
        image: postgres
        restart: unless-stopped
        container_name: postgres
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        expose:
            - "5432"

volumes:
    postgres-data:

networks:
    default:
        external:
            name: nginx-proxy
