version: "3.8"
services:
    postgres:
        image: postgres:15.1
        restart: unless-stopped
        container_name: postgres
        environment:
            POSTGRES_DB: juicify
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        expose:
            - "5432"
        labels:
            - "traefik.enable=true"
            - "traefik.tcp.routers.postgres.entrypoints=postgres"
            - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
            - "traefik.tcp.routers.postgres.tls=false"
            - "traefik.tcp.services.postgres.loadBalancer.server.port=5432"
            - "traefik.tcp.routers.postgres.service=postgres"

    redis:
        image: redis:latest
        restart: unless-stopped
        container_name: redis
        ports:
            - "6379:6379"
        expose:
            - "6379"
        volumes:
            - redis_data:/data

    # prometheus:
    #     image: prom/prometheus:latest
    #     restart: unless-stopped
    #     container_name: prometheus
    #     volumes:
    #         - ./prometheus/:/etc/prometheus/
    #         - prometheus-data:/prometheus
    #     ports:
    #         - "9090:9090"
    #     command: "--config.file=/etc/prometheus/prometheus.yml"

    # grafana:
    #     image: grafana/grafana-oss:latest
    #     restart: unless-stopped
    #     container_name: grafana
    #     volumes:
    #         - grafana-data:/var/lib/grafana
    #     ports:
    #         - "3000:3000"

    # node_exporter:
    #     image: quay.io/prometheus/node-exporter:latest
    #     restart: unless-stopped
    #     container_name: node_exporter
    #     volumes:
    #         - "/:/host:ro,rslave"
    #     pid: host
    #     command:
    #         - "--path.rootfs=/host"

    # cadvisor:
    #     # TODO: latest tag is not updated, check latest release https://github.com/google/cadvisor/releases
    #     image: gcr.io/cadvisor/cadvisor:v0.45.0
    #     container_name: cadvisor
    #     restart: unless-stopped
    #     volumes:
    #         - /:/rootfs:ro
    #         - /var/run:/var/run:ro
    #         - /sys:/sys:ro
    #         - /var/lib/docker/:/var/lib/docker:ro
    #         - /dev/disk/:/dev/disk:ro
    #     ports:
    #         - "8080:8080"
    #     network_mode: host
    #     devices:
    #         - /dev/kmsg
    #     privileged: true

volumes:
    postgres-data:
    redis_data:
    # prometheus-data:
    # grafana-data:
