version: "3.8"
services:
    postgres:
        image: postgres:15.1
        restart: unless-stopped
        container_name: postgres
        environment:
            POSTGRES_DB: juicify
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        volumes:
            - postgres-data:/var/lib/postgresql/data
        expose:
            - "5432"
        labels:
            - "traefik.enable=true"
            - "traefik.tcp.routers.postgres.entrypoints=postgres"
            - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
            - "traefik.tcp.routers.postgres.tls=false"
            - "traefik.tcp.services.postgres.loadBalancer.server.port=5432"
            - "traefik.tcp.routers.postgres.service=postgres"

    nextjs:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: nextjs
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        expose:
            - "3000"
        depends_on:
            - postgres
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nextjs.rule=Host(`juicify.app`)"
            - "traefik.http.routers.nextjs.entrypoints=websecure"
            - "traefik.http.routers.nextjs.tls.certresolver=myresolver"
            - "traefik.tcp.routers.postgres.entrypoints=postgres"
        command: npm run start

volumes:
    postgres-data:

networks:
    default:
        external:
            name: traefik-net
