version: "3.8"
services:
    postgres:
        image: postgres:15.1
        restart: unless-stopped
        container_name: postgres
        environment:
            POSTGRES_DB: juicify
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: "!Preetini49e89d5b"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        expose:
            - "5432"

    nextjs:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: nextjs
        environment:
            DATABASE_URL: postgres://admin:!Preetini49e89d5b@postgres:5432/juicify
            NEXTAUTH_URL: https://juicify.app
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        expose:
            - "3000"
        depends_on:
            - postgres
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=Host(`juicify.app`)"
            - "traefik.http.routers.whoami.entrypoints=websecure"
            - "traefik.http.routers.whoami.tls.certresolver=myresolver"
        command: npm run dev

volumes:
    postgres-data:

networks:
    default:
        external:
            name: traefik-net
