# Generated by Django 3.2 on 2022-09-03 13:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('goal', models.IntegerField(choices=[(-4, -1.5), (-3, -1.25), (-2, -1), (-1, -0.5), (0, 0), (1, 0.5), (2, 1), (3, 1.25), (4, 1.5)], default=0, validators=[django.core.validators.MinValueValidator(-4), django.core.validators.MaxValueValidator(4)])),
                ('kind_of_diet', models.IntegerField(choices=[(0, 'REGULAR'), (1, 'KETOGENIC')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('activity_level', models.IntegerField(choices=[(0, 1.2), (1, 1.375), (2, 1.55), (3, 1.715), (4, 1.9)], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('data', models.JSONField(blank=True, default=list, null=True)),
                ('is_sport_active', models.BooleanField(default=True)),
                ('is_coach_analyze', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
