# Generated by Django 3.2 on 2022-09-11 13:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='coach',
            name='bmr',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='counted_carbs',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='coach',
            name='counted_fats',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='coach',
            name='counted_proteins',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='coach',
            name='data_coverage_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='coach',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1000'))]),
        ),
        migrations.AlterField(
            model_name='coach',
            name='activity_level',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0),
        ),
        migrations.AlterField(
            model_name='coach',
            name='goal',
            field=models.DecimalField(choices=[(-1.5, -1.5), (-1.25, -1.25), (-1, -1), (-0.75, -0.75), (-0.5, -0.5), (0, 0), (0.5, 0.5), (0.75, 0.75), (1, 1), (1.25, 1.25), (1.5, 1.5)], decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='coach',
            name='kind_of_diet',
            field=models.IntegerField(choices=[(0, 'REGULAR'), (1, 'KETOGENIC')], default=0),
        ),
    ]
