# Generated by Django 3.2 on 2022-09-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_auto_20220911_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
