# Generated by Django 3.2 on 2022-09-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_coach_analyze'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='coach',
            new_name='next_coach',
        ),
    ]
