# Generated by Django 3.2 on 2022-09-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_coach_customuser_next_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activity_level',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='goal',
            field=models.DecimalField(choices=[(-1.5, -1.5), (-1.25, -1.25), (-1, -1), (-0.75, -0.75), (-0.5, -0.5), (0, 0), (0.5, 0.5), (0.75, 0.75), (1, 1), (1.25, 1.25), (1.5, 1.5)], decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kind_of_diet',
            field=models.IntegerField(choices=[(0, 'REGULAR'), (1, 'KETOGENIC')], default=0),
        ),
    ]
