# Generated by Django 3.2 on 2022-09-14 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220911_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirm_email_hash',
            field=models.CharField(default=uuid.uuid4, editable=False, help_text='Hash used to confirm email', max_length=36),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_confirm_email_hash_expired',
            field=models.BooleanField(default=False),
        ),
    ]
