name: CI-SFTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: arjen
          server: 194.59.158.13
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_path: '/home/arjen/juicify'
          args: '-o ConnectTimeout=5'
          delete_remote_files: true
  create-env:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          directory: '../../home/arjen/juicify'
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
