name: CI-SFTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: arjen
          server: 194.59.158.13
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_path: '/home/arjen/juicify'
          args: '-o ConnectTimeout=5'
  
  prisma-generate:
    runs-on: ubuntu-latest
    needs: deploy-via-sftp

    steps:
      - name: Regenerating prisma's types
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: npx prisma generate --prefix ./juicify
          host: 194.59.158.13
          port: 22
          username: arjen
          passphrase: ${{ secrets.FTP_PASSWORD }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
  
  restart-dockers:
    runs-on: ubuntu-latest
    needs: prisma-generate

    steps:
      - name: Restarting dockers related to deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker-compose -f ./juicify/Docker-compose.yml up --build -d
          host: 194.59.158.13
          port: 22
          username: arjen
          passphrase: ${{ secrets.FTP_PASSWORD }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
