name: CI-SFTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: arjen
          server: 194.59.158.13
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_path: '/home/arjen/juicify'
          args: '-o ConnectTimeout=5'
      # - run: docker-compose -f Docker-compose.yml up --build -d
